update space configurations

diff --git a/.github/workflows/deploy-production.yml b/.github/workflows/deploy-production.yml
--- a/.github/workflows/deploy-production.yml
+++ b/.github/workflows/deploy-production.yml
@@ -109,6 +109,9 @@ jobs:
       PONTO_PRIVATE_KEY_PASSWORD: ${{ secrets.PONTO_PRIVATE_KEY_PASSWORD }}
       PONTO_SIGNATURE_KEY_ID: ${{ secrets.PONTO_SIGNATURE_KEY_ID }}
       FERNET_KEY: ${{ secrets.FERNET_KEY }}
+      DIGITAL_OCEAN_SPACES_KEY: ${{ secrets.DIGITAL_OCEAN_SPACES_KEY }}
+      DIGITAL_OCEAN_SPACES_SECRET: ${{ secrets.DIGITAL_OCEAN_SPACES_SECRET }}
+      DIGITAL_OCEAN_SPACES_NAME: ${{ secrets.DIGITAL_OCEAN_SPACES_NAME }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -126,6 +129,8 @@ jobs:
           cat <<EOF > .env
           POSTGRES_USER=${POSTGRES_USER}
           POSTGRES_DB=${POSTGRES_DB}
+          POSTGRES_DB_URL=${POSTGRES_DB_URL}
+          POSTGRES_PORT=${POSTGRES_PORT}
           POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
           MINIO_USER=${MINIO_USER}
           MINIO_PASSWORD=${MINIO_PASSWORD}
@@ -142,6 +147,9 @@ jobs:
           PONTO_PRIVATE_KEY_PASSWORD=${PONTO_PRIVATE_KEY_PASSWORD}
           PONTO_SIGNATURE_KEY_ID=${PONTO_SIGNATURE_KEY_ID}
           FERNET_KEY=${FERNET_KEY}
+          DIGITAL_OCEAN_SPACES_KEY=${DIGITAL_OCEAN_SPACES_KEY}
+          DIGITAL_OCEAN_SPACES_SECRET=${DIGITAL_OCEAN_SPACES_SECRET}
+          DIGITAL_OCEAN_SPACES_NAME=${DIGITAL_OCEAN_SPACES_NAME}
           EOF
           cd ..
 
@@ -180,7 +188,7 @@ jobs:
             export BACKEND_IMAGE=${{ env.REGISTRY }}/${REPO_NAME}/backend:${{ github.sha }}
             docker compose --env-file .env -f docker-compose.prod.yml config > previous_config.yaml || { echo "Failed to preserve previous state"; exit 1; }
             docker compose --env-file .env -f docker-compose.prod.yml pull || { echo "Failed to pull images"; exit 1; }
-            docker compose --env-file .env -f docker-compose.prod.yml up -d --force-recreate || { echo "Failed to deploy services"; exit 1; }
+            docker compose --env-file .env -f docker-compose.prod.yml up -d --force-recreate stable || { echo "Failed to deploy stable services"; exit 1; }
 
       - name: Rollback on failure
         if: failure()
@@ -193,4 +201,4 @@ jobs:
             cd /home/billify/app/infrastructure/
             echo "Rolling back to previous configuration..."
             mv -f previous_config.yaml docker-compose.prod.yml
-            docker compose -f docker-compose.prod.yml up -d --force-recreate
+            docker compose -f docker-compose.prod.yml up -d --force-recreate stable
